services:
  db:
    image: postgres:16-alpine
    container_name: wh_portal_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: warhammer_portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

