# Generated by Django 5.1.4 on 2026-02-24 08:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_public', models.BooleanField(default=True, verbose_name='public')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='collections/', verbose_name='cover image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collections',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GameSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='game_systems/', verbose_name='logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'game system',
                'verbose_name_plural': 'game systems',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Miniature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('faction', models.CharField(blank=True, max_length=200, verbose_name='faction')),
                ('unit_type', models.CharField(blank=True, max_length=200, verbose_name='unit type')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('paint_status', models.CharField(choices=[('unpainted', 'Unpainted'), ('wip', 'Work in Progress'), ('painted', 'Painted'), ('based', 'Based'), ('display_ready', 'Display Ready')], default='unpainted', max_length=20, verbose_name='paint status')),
                ('points_cost', models.PositiveIntegerField(blank=True, default=0, verbose_name='points cost')),
                ('image', models.ImageField(blank=True, null=True, upload_to='miniatures/', verbose_name='image')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'miniature',
                'verbose_name_plural': 'miniatures',
                'ordering': ['name'],
            },
        ),
    ]
