# Generated by Django 5.1.4 on 2026-02-24 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collection',
            name='game_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='collections.gamesystem'),
        ),
        migrations.AddField(
            model_name='miniature',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miniatures', to='collections.collection'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('user', 'name')},
        ),
    ]
